# Generated by Django 3.0.8 on 2020-08-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preson',
            new_name='Person',
        ),
    ]
