# Generated by Django 3.0.8 on 2020-08-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0002_auto_20200821_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='temptareture',
            new_name='temp',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created',
        ),
    ]
